[book]
authors = ["0xax"]
language = "en"
multilingual = false
src = "./"
title = "Linux Insides"

[output.html]
additional-css = ["theme/custom.css"]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/0xAX/linux-insides/"
git-repository-icon = "fa-github"